export const WORDS = [
  'AGENT',
  'WORLD',
  'ABOUT',
  'HEART',
  'WATER',
  'SIXTY',
  'BOARD',
  'MONTH',
  'MUSIC',
  'PARTY',
  'PIANO',
  'MOUTH',
  'WOMAN',
  'SUGAR',
  'AMBER',
  'DREAM',
  'LAUGH',
  'TIGER',
  'EARTH',
  'RIVER',
  'MONEY',
  'WORDS',
  'SMILE',
  'LEMON',
  'SOUTH',
  'AFTER',
  'STONE',
  'THING',
  'LIGHT',
  'STORY',
  'POWER',
  'TODAY',
  'RANGE',
  'PEARL',
  'VENOM',
  'PROXY',
  'ROUND',
  'HOVER',
  'CANDY',
  'ABOVE',
  'PHONE',
  'OTHER',
  'SMART',
  'BLACK',
  'CYCLE',
  'MAGIC',
  'FRUIT',
  'RADIO',
  'ROYAL',
  'HONEY',
];

export const KEYBOARD_LEETERS = [
  ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O', 'P'],
  ['A', 'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L'],
  ['Z', 'X', 'C', 'V', 'B', 'N', 'M']
];

export const DEFAULT_LETTERS = {
    A: "incorrect",
    B: "incorrect",
    C: "incorrect",
    D: "incorrect",
    E: "incorrect",
    F: "incorrect",
    G: "incorrect",
    H: "incorrect",
    I: "incorrect",
    J: "incorrect",
    K: "incorrect",
    L: "incorrect",
    M: "incorrect",
    N: "incorrect",
    O: "incorrect",
    P: "incorrect",
    Q: "incorrect",
    R: "incorrect",
    S: "incorrect",
    T: "incorrect",
    U: "incorrect",
    V: "incorrect",
    W: "incorrect",
    X: "incorrect",
    Y: "incorrect",
    Z: "incorrect",
  }